import {
    pgTable, uuid, text, integer, boolean, numeric,
    timestamp, jsonb, date, time,
  } from 'drizzle-orm/pg-core';
  import { sql } from 'drizzle-orm';
  import {
    leadStatusEnum, pipelineStageEnum, temperatureEnum, optInStatusEnum,
    sendStatusEnum, taskStatusEnum, bookingStatusEnum,
    contentStatusEnum, contentTypeEnum, callStatusEnum,
  } from './enums';
  
  export const agencySettings = pgTable('agency_settings', {
    agencyId:                      uuid('agency_id').primaryKey().defaultRandom(),
    agencyName:                    text('agency_name').notNull(),
    defaultLanguage:               text('default_language').notNull().default('en'),
    tone:                          text('tone').notNull().default('professional'),
    timezone:                      text('timezone').notNull().default('UTC'),
    workingHours:                  jsonb('working_hours').notNull().default(sql`'[]'::jsonb`),
    followupSequences:             jsonb('followup_sequences').notNull().default(sql`'[]'::jsonb`),
    channelsEnabled:               jsonb('channels_enabled').notNull().default(sql`'{}'::jsonb`),
    bookingEnabled:                boolean('booking_enabled').notNull().default(false),
    humanApprovalRequired:         boolean('human_approval_required').notNull().default(true),
    whatsappAutomationEnabled:     boolean('whatsapp_automation_enabled').notNull().default(false),
    hotLeadScoreThreshold:         integer('hot_lead_score_threshold').notNull().default(70),
    superHotScoreThreshold:        integer('super_hot_score_threshold').notNull().default(85),
    dataRetentionDays:             integer('data_retention_days').notNull().default(730),
    createdAt:                     timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt:                     timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  });
  
  export const leads = pgTable('leads', {
    id:                        uuid('id').primaryKey().defaultRandom(),
    agencyId:                  uuid('agency_id').notNull().references(() => agencySettings.agencyId),
    fullName:                  text('full_name'),
    phone:                     text('phone'),
    email:                     text('email'),
    dedupKey:                  text('dedup_key'),
    source:                    text('source'),
    sourceType:                text('source_type'),
    channel:                   text('channel'),
    message:                   text('message'),
    campaignId:                text('campaign_id'),
    utmSource:                 text('utm_source'),
    utmCampaign:               text('utm_campaign'),
    budgetRaw:                 text('budget_raw'),
    locationInterestRaw:       text('location_interest_raw'),
    rawPayload:                jsonb('raw_payload'),
    receivedAt:                timestamp('received_at', { withTimezone: true }),
    score:                     integer('score'),
    temperature:               temperatureEnum('temperature'),
    urgency:                   text('urgency'),
    intent:                    text('intent'),
    languageDetected:          text('language_detected'),
    budgetExtracted:           numeric('budget_extracted'),
    locationInterestExtracted: text('location_interest_extracted'),
    nextAction:                text('next_action'),
    recommendedChannel:        text('recommended_channel'),
    reasoningSummary:          text('reasoning_summary'),
    scoredAt:                  timestamp('scored_at', { withTimezone: true }),
    status:                    leadStatusEnum('status').notNull().default('active'),
    pipelineStage:             pipelineStageEnum('pipeline_stage').notNull().default('new'),
    optInStatus:               optInStatusEnum('opt_in_status').notNull().default('unknown'),
    optInAt:                   timestamp('opt_in_at', { withTimezone: true }),
    followupPaused:            boolean('followup_paused').notNull().default(false),
    humanOwnerActive:          boolean('human_owner_active').notNull().default(false),
    followupCount:             integer('followup_count').notNull().default(0),
    nextFollowupAt:            timestamp('next_followup_at', { withTimezone: true }),
    lastFollowupAt:            timestamp('last_followup_at', { withTimezone: true }),
    lastContactAt:             timestamp('last_contact_at', { withTimezone: true }),
    lastInboundWhatsappAt:     timestamp('last_inbound_whatsapp_at', { withTimezone: true }),
    missedCallCaptured:        boolean('missed_call_captured').notNull().default(false),
    callSummary:               text('call_summary'),
    lastCallAt:                timestamp('last_call_at', { withTimezone: true }),
    conversationId:            uuid('conversation_id'),
    gdprErasureRequestedAt:    timestamp('gdpr_erasure_requested_at', { withTimezone: true }),
    gdprErasedAt:              timestamp('gdpr_erased_at', { withTimezone: true }),
    createdAt:                 timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt:                 timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  });
  
  export const leadEvents = pgTable('lead_events', {
    id:             uuid('id').primaryKey().defaultRandom(),
    leadId:         uuid('lead_id').notNull().references(() => leads.id),
    agencyId:       uuid('agency_id').notNull(),
    type:           text('type').notNull(),
    source:         text('source').notNull(),
    channel:        text('channel'),
    platform:       text('platform'),
    content:        text('content'),
    summary:        text('summary'),
    conversationId: uuid('conversation_id'),
    rawPayload:     jsonb('raw_payload').notNull().default(sql`'{}'::jsonb`),
    timestamp:      timestamp('timestamp', { withTimezone: true }).notNull().defaultNow(),
  });
  
  export const sendQueue = pgTable('send_queue', {
    id:                uuid('id').primaryKey().defaultRandom(),
    idempotencyKey:    text('idempotency_key').notNull().unique(),
    agencyId:          uuid('agency_id').notNull(),
    leadId:            uuid('lead_id').notNull().references(() => leads.id),
    channel:           text('channel').notNull(),
    hub:               text('hub').notNull(),
    templateKey:       text('template_key').notNull(),
    templateVariables: jsonb('template_variables').notNull().default(sql`'{}'::jsonb`),
    priority:          text('priority').notNull().default('normal'),
    status:            sendStatusEnum('status').notNull().default('queued'),
    requestedBy:       text('requested_by').notNull(),
    requestedAt:       timestamp('requested_at', { withTimezone: true }).notNull().defaultNow(),
    expiryAt:          timestamp('expiry_at', { withTimezone: true }).notNull(),
    sendAfter:         timestamp('send_after', { withTimezone: true }),
    providerMessageId: text('provider_message_id'),
    providerResponse:  jsonb('provider_response'),
    sentAt:            timestamp('sent_at', { withTimezone: true }),
    failedAt:          timestamp('failed_at', { withTimezone: true }),
    failureReason:     text('failure_reason'),
    isRetryable:       boolean('is_retryable'),
    retryCount:        integer('retry_count').notNull().default(0),
    maxRetries:        integer('max_retries').notNull().default(2),
    nextRetryAt:       timestamp('next_retry_at', { withTimezone: true }),
    createdAt:         timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt:         timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  });
  
  export const dashboardTasks = pgTable('dashboard_tasks', {
    id:              uuid('id').primaryKey().defaultRandom(),
    agencyId:        uuid('agency_id').notNull(),
    leadId:          uuid('lead_id').notNull().references(() => leads.id),
    taskType:        text('task_type').notNull(),
    status:          taskStatusEnum('status').notNull().default('pending'),
    title:           text('title').notNull(),
    description:     text('description'),
    messageBody:     text('message_body'),
    messageSubject:  text('message_subject'),
    channel:         text('channel'),
    priority:        text('priority').notNull().default('normal'),
    temperature:     text('temperature'),
    leadScore:       integer('lead_score'),
    suggestedAction: text('suggested_action'),
    assignedTo:      text('assigned_to'),
    handledBy:       text('handled_by'),
    dueAt:           timestamp('due_at', { withTimezone: true }),
    handledAt:       timestamp('handled_at', { withTimezone: true }),
    rawPayload:      jsonb('raw_payload'),
    createdAt:       timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt:       timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  });
  
  export const bookings = pgTable('bookings', {
    id:                 uuid('id').primaryKey().defaultRandom(),
    agencyId:           uuid('agency_id').notNull().references(() => agencySettings.agencyId),
    leadId:             uuid('lead_id').notNull().references(() => leads.id),
    propertyId:         uuid('property_id'),
    bookingType:        text('booking_type').notNull(),
    status:             bookingStatusEnum('status').notNull().default('requested'),
    scheduledAt:        timestamp('scheduled_at', { withTimezone: true }),
    durationMinutes:    integer('duration_minutes'),
    location:           text('location'),
    agentName:          text('agent_name'),
    agentId:            text('agent_id'),
    externalCalendarId: text('external_calendar_id'),
    confirmationSent:   boolean('confirmation_sent').notNull().default(false),
    reminderSent:       boolean('reminder_sent').notNull().default(false),
    notes:              text('notes'),
    createdAt:          timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt:          timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  });
  
  export const aiClassifications = pgTable('ai_classifications', {
    id:                  uuid('id').primaryKey().defaultRandom(),
    agencyId:            uuid('agency_id').notNull(),
    leadId:              uuid('lead_id').references(() => leads.id),
    serviceSource:       text('service_source').notNull(),
    classificationType:  text('classification_type').notNull(),
    inputText:           text('input_text'),
    output:              jsonb('output').notNull(),
    classification:      text('classification'),
    confidence:          numeric('confidence', { precision: 4, scale: 3 }),
    requiresHumanReview: boolean('requires_human_review').notNull().default(false),
    routingDecision:     text('routing_decision'),
    modelUsed:           text('model_used').notNull(),
    tokensUsed:          integer('tokens_used'),
    costUsd:             numeric('cost_usd', { precision: 10, scale: 6 }),
    classifiedAt:        timestamp('classified_at', { withTimezone: true }).notNull().defaultNow(),
  });
  
  export const incidents = pgTable('incidents', {
    id:                 uuid('id').primaryKey().defaultRandom(),
    agencyId:           uuid('agency_id'),
    incidentType:       text('incident_type').notNull(),
    severity:           text('severity').notNull(),
    sourceService:      text('source_service').notNull(),
    affectedEntityType: text('affected_entity_type'),
    affectedEntityId:   uuid('affected_entity_id'),
    description:        text('description').notNull(),
    status:             text('status').notNull().default('open'),
    resolvedAt:         timestamp('resolved_at', { withTimezone: true }),
    createdAt:          timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt:          timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  });
  
  export const contentItems = pgTable('content_items', {
    id:               uuid('id').primaryKey().defaultRandom(),
    agencyId:         uuid('agency_id').notNull().references(() => agencySettings.agencyId),
    contentType:      contentTypeEnum('content_type').notNull(),
    platform:         text('platform').notNull().default('none'),
    title:            text('title').notNull(),
    body:             text('body').notNull(),
    mediaUrls:        jsonb('media_urls').notNull().default(sql`'[]'::jsonb`),
    status:           contentStatusEnum('status').notNull().default('draft'),
    approvedBy:       text('approved_by'),
    approvedAt:       timestamp('approved_at', { withTimezone: true }),
    scheduledFor:     timestamp('scheduled_for', { withTimezone: true }),
    publishedAt:      timestamp('published_at', { withTimezone: true }),
    propertyId:       uuid('property_id'),
    tone:             text('tone'),
    aiPromptUsed:     text('ai_prompt_used'),
    tokensUsed:       integer('tokens_used'),
    costUsd:          numeric('cost_usd', { precision: 10, scale: 6 }),
    createdBy:        text('created_by'),
    createdAt:        timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt:        timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  });