import { z } from "zod";

// ---- Library ----
export const FontEntry = z.object({
  id: z.string(),
  declared_family: z.string(), // asserted internal family name (checked against the TTF name table)
  label: z.string().optional(), // human-friendly name (e.g. "Libre Caslon Text" when the TTF internal name is "LCText400")
  file: z.string(),
  category: z.enum(["serif", "sans", "script", "display"]),
  weight: z.number().int().min(100).max(900),
  style: z.enum(["normal", "italic"]),
  license_ok: z.boolean(),
  // test-only: force the loader to render the validation probe by declared_family (simulates the multi-word fallback footgun)
  force_render_by_declared: z.boolean().optional(),
});
export type FontEntry = z.infer<typeof FontEntry>;

export const FontLibraryFile = z.object({
  library_version: z.string(),
  fonts: z.array(FontEntry).min(1),
});

// ---- Job ----
export const LayerSpec = z.object({
  layer_id: z.string(),
  text: z.string(),
  layer_bbox: z.tuple([z.number(), z.number(), z.number(), z.number()]),
  ref_glyph_bbox: z.tuple([z.number(), z.number(), z.number(), z.number()]).optional(),
  metric: z.enum(["cap", "x"]),
  match_mode: z.enum(["shape", "metric"]).default("shape"), // shape = render+align (needs known text); metric = content-independent (stem/ratio/contrast)
  categories: z.array(z.enum(["serif", "sans", "script", "display"])).optional(),
  ground_truth: z.object({ family: z.string(), weight: z.number().optional(), style: z.string().optional() }).optional(),
});
export type LayerSpec = z.infer<typeof LayerSpec>;

export const ResolveJob = z.object({
  template_id: z.string(),
  source_render: z.string(),
  source_svg: z.string().optional(), // if the png must be generated by the existing renderer
  layers: z.array(LayerSpec).min(1),
});
export type ResolveJob = z.infer<typeof ResolveJob>;

// ---- Results ----
export interface CandidateScore {
  font_id: string; family: string; weight: number; style: string;
  composite: number; shape: number; stem: number; spacing: number; pixel: number; metric_fit: number;
  rendered_ok: boolean;
  visual_match_score?: number;
}

export type VisualLabel = "exact_metadata_match" | "verified_visual_match" | "visual_substitute" | "needs_seed";
export interface LayerResult {
  layer_id: string;
  decision: "accept" | "review" | "fail";
  confidence: number;
  best: CandidateScore;
  runner_up: CandidateScore | null;
  separation: number;
  top: CandidateScore[];
  match_mode: string;
  measurement_quality: string;
  manifest_mapping: { family: string; file: string; weight: number; style: string } | null;
  ground_truth_check?: { matched: boolean; true_font_rank: number | null; true_font_composite: number | null };
  proof: { overlay: string; contact_sheet: string };
  notes: string[];
}
export interface ResolverReport {
  template_id: string; run_at: string; library_version: string;
  thresholds: { high: number; high_separation: number; medium: number };
  weights: Record<string, number>;
  layers: LayerResult[];
  summary: { accepted: number; review: number; fail: number };
  ready_for_next: boolean;
}

export const THRESHOLDS = { high: 0.85, high_separation: 0.06, medium: 0.7 };
// composite weights (provisional; calibrated on #4). stem ~= shape because IoU/pixel are weight-confounded.
export const WEIGHTS = { shape: 0.35, stem: 0.3, spacing: 0.15, pixel: 0.1, metric_fit: 0.1 };
