// ─────────────────────────────────────────────────────────────────────────────
// SURGICAL WATERMARK REMOVAL (Christian 2026-07-19). Replaces the seedream "clean up"
// that REPAINTED the whole photo (moved furniture, reframed the house). This is the
// opposite: it only ever alters the watermark's own pixels and leaves every other
// pixel byte-identical — no house drift is possible by construction.
//
// HOW: montinmo stamps an IDENTICAL semi-transparent "MONTINMO REAL ESTATE" logo at a
// FIXED position on every 1280x1024 "_w_xl" photo (proven by median-stacking 60 varied
// photos — the logo emerges razor-sharp, everything else averages to noise). So we ship
// a CALIBRATED binary mask of exactly those letter pixels (~0.84% of the frame) and fill
// only them by 8-direction distance-weighted interpolation from their real neighbours.
// Everything outside the mask is copied through unchanged.
//
// SAFETY: only fires on the calibrated size (1280x1024). Any other size, or any error,
// returns null → the caller MUST use the original photo untouched. A visible watermark
// is acceptable; a silently altered house is not. Never falls back to a generative edit.
// ─────────────────────────────────────────────────────────────────────────────
import sharp from 'sharp';

const W = 1280, H = 1024, PX = W * H;
const MASK_PNG_B64 = 'iVBORw0KGgoAAAANSUhEUgAABQAAAAQACAIAAAAx8WMUAAAACXBIWXMAAAPoAAAD6AG1e1JrAAAUkklEQVR42u3dy5LbOBJAUf7/T6sXjuhwWPUAgcxEgjpnNdN2USRNLW4BBK4LAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADY4fV6uQkAAAA8v37/0Oorp+SXCAAAAGfUb2oD/3Pw///v3Q+tbPXBT3m/gUoYAACge/1+15aLzfnehyMfuqvVb5X263uGxwEAAFrX73tBvf/R3Jjtr0JavXJUfPGKPnwqOwAAwP4Afp+rHDVmG9vAe0fFB6/uYVPZAQAAnhnAIXUXGMA1g5yBAdxtKjsAAIAGnqnfjAa+dr/meuvE+sx/FsAAAACT4RTYq+E53eG96IYrYKlfAACAyXD6dWQ478XjUwL4h7vUczVvAAAA9ft1Nf3w3x9caytLc7VdzAwAAED9Dq0C/Wlb18695Nz53xEAAED9aqeOTWsKNAAAQFH9Kqhn/IO6MwAAgFh6aWABDAAAoH4V1HP2cwYAABBL6vcjtrMCAAAQS+pXAAMAAHzYKsf/VNOWfNJspkADAAAcuYTSrWO+F/j66PTiFY1vkrziu8Hbf/7oh0+8dbF3z6T+SbBTFwAAsG06dMExF+txOl9/GIh+HeUamwId8ik1T5el2gAAgDNeBr51zKj8Cxk5fB3ry4H08EsreLrqEx0AAFC/8TOHaxo4L5tPaeDUSzvoSQAAAEicZTpxzNRpwOHZfEQDZ4d9+JMQe56+2gAAQEylxB6w4FVYDZx0n2OHf+vPEAAA0MCvleWjNtavBu7TwHvrVwMDAADpbwJvr9+oBn7M+8ATCzKnrr9dVr8aGAAASGzgpOwpK6vma2JF/Uv1CeCVfyMNDAAAHBPABYkVMrs7fFL3dFp3C+D1J2F9Fy4BDAAAbAjg8LHZ9RMOWeY677oKAvjuFdUHcM2se99uAAAgcims+rc3twfw339666ze/3JNOYcH8PqvDMqeBAAAgJgA7r/NbGoursRYwdDx+Bk2DOCoJ8EXHAAAuELGFXct3rt3uanY0cjUAB788eInIXDwVgADAAACOHEjJQF80JPgCw4AAFzrE2snfqp/AI9c3VkBPH5FZU9CYLUKYAAAIDeApxeaKsue9QB7UgAPXpEABgAABHBFVbYK4LOmQK/fkA53VQADAAACOPico3KxVQCv3xMBDAAACOC6AK55BzjqCAJYAAMAAAJYAG8I4NRVss59EnzBAQCATw/g9VxsGMCLWyUJYAAAQAD3yp7ANZyfF8CtFnPu8CQAAAA0DeCRaIndxOh5ATy3Q9VTnwQAAIChirgVRdfYIs+L0ZKxi68AfuST4KsNAAB0D+CVVhxsucVi7B/Ac1f0yCcBAABgNICjsnNi9amJnBu/qMcH8N1kfeqTAAAAEPM+7fSk1tTNY5MKdv3H817AXmzgwWoNf793+zbCAACA+s2a0ZrXwCEjhNM/O9dmNdUXW60hx8luYF9tAAAga/Hn6SnEu+o3diC3z5LLe1f5brL9kq82AACQOPm2LFljD3VFLC/cMyk/toF9rwEAgIBlnwIDODDPwteyurWG00r8F0/9Lfh9x94nQf0CAAAx7wB/9/crV5DKfo938DiBK0gXT/1dD9ezngQAAIClzXsWh++iBqVjL2r8OFG/SriqVoEev6JDnwT1CwAARO4D/OXfX5w5HDL9OGoId/AgSdWdtw/w3SsKfxL+/I/3Iyc9mQAAAAAAAAAAAAAAAAAAAAAAAFzBq5S5DwAAAA/ZbXhuN527u+AWLBwdcv4ri0LPLUO9vj9T4EZWAAAAT67fxbr7uanWtyPKvvC7W/JGbRccdfPz9i4GAAB4YP0u1t347sRzp5p94YvXPnGLtpyABgYAANRvSlPNdeBKsL3aa3WevikAAIAAThnhXJzx+4wA7hnkAAAAGjg9gPtMgS67RQIYAADg+Aa+9elXp0WwjAADAABo4JT6ndt8SACrXwAAgKIUHFzbuXMA731Hus+yW74dAACAAM5a/Hl60LjVVd+9wJX6/fW2GPsFAACongz8OQH8d3kOnvl0/eYdXAMDAAACOKCm5n7wrHeAkxa7nr4tAhgAABDAwaOOgfv6Hh3Ad888+7YIYAAAQABXRGzIzx4awE1uiwAGAAAEcJeIbR7AST8lgAEAAJ45BbomgH/tt7LzHwzgpBWnBTAAAEDHsdCM0jtlBLjVytsCGAAAEMA7o+6aXUpq4qqvuNWbR46zfeupH/6CLwgAAGAf4JNs3/24eQAbBwYAAATwq892QScG8OLHrZ+wAAYAAOg1/PvIAA75rKh8jb17AAAA6jfrFd/YAO6zCfD2OyOAAQAAAfzYAD6rfnu+QQ0AAKCBO06Brr/qwM+KOoj6BQAAuLaPZKbWaf0+wIG9HXsQ9QsAAHBtHMm8ez6B/RaekdN3OC+kQy4ZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACgzH8zBAoMUd0CgAAAAABJRU5ErkJggg==';

let MASK: Uint8Array | null = null;
let BOUNDS: { x0: number; y0: number; x1: number; y1: number } | null = null;

async function ensureMask(): Promise<{ mask: Uint8Array; bounds: NonNullable<typeof BOUNDS> }> {
  if (MASK && BOUNDS) return { mask: MASK, bounds: BOUNDS };
  const raw = await sharp(Buffer.from(MASK_PNG_B64, 'base64')).greyscale().raw().toBuffer();
  const mask = new Uint8Array(PX);
  let x0 = W, y0 = H, x1 = 0, y1 = 0;
  for (let p = 0; p < PX; p++) {
    if (raw[p] > 127) { mask[p] = 1; const x = p % W, y = (p / W) | 0; if (x < x0) x0 = x; if (x > x1) x1 = x; if (y < y0) y0 = y; if (y > y1) y1 = y; }
  }
  MASK = mask; BOUNDS = { x0, y0, x1, y1 };
  return { mask, bounds: BOUNDS };
}

/**
 * Remove the montinmo watermark from a listing photo. Returns a PNG buffer with ONLY the
 * watermark pixels changed, or null if the photo is not the calibrated montinmo size (the
 * caller then keeps the original). Fast (~50ms), deterministic, no network, no AI, no cost.
 */
export async function removeMontinmoWatermark(input: Buffer): Promise<Buffer | null> {
  try {
    const meta = await sharp(input).metadata();
    if (meta.width !== W || meta.height !== H) return null;
    const { mask, bounds } = await ensureMask();
    const src = await sharp(input).removeAlpha().raw().toBuffer();
    const out = Buffer.from(src);
    const LIM = 90;
    const dirs = [[1, 0], [-1, 0], [0, 1], [0, -1], [1, 1], [-1, -1], [1, -1], [-1, 1]];
    for (let y = bounds.y0 - 2; y <= bounds.y1 + 2; y++) {
      for (let x = bounds.x0 - 2; x <= bounds.x1 + 2; x++) {
        const p = y * W + x;
        if (p < 0 || p >= PX || !mask[p]) continue;
        let r = 0, g = 0, b = 0, ws = 0;
        for (const [dx, dy] of dirs) {
          let d = 1;
          while (d < LIM) {
            const qx = x + dx * d, qy = y + dy * d;
            if (qx < 0 || qx >= W || qy < 0 || qy >= H) break;
            const q = qy * W + qx;
            if (!mask[q]) { const w = 1 / (d * d); r += src[q * 3] * w; g += src[q * 3 + 1] * w; b += src[q * 3 + 2] * w; ws += w; break; }
            d++;
          }
        }
        if (ws > 0) { out[p * 3] = Math.round(r / ws); out[p * 3 + 1] = Math.round(g / ws); out[p * 3 + 2] = Math.round(b / ws); }
      }
    }
    return await sharp(out, { raw: { width: W, height: H, channels: 3 } }).png().toBuffer();
  } catch (err) {
    console.error('[watermark] removeMontinmo failed:', (err as Error).message);
    return null;
  }
}
